import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ReactNode } from 'react';
import FirebaseProvider from '../components/FirebaseProvider';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Initialize the Open Sans font
const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap", // This helps with font loading
  variable: "--font-open-sans", // Add a CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Unique Stores</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body>
        <Toaster position="top-left" />
        <FirebaseProvider>
          {children}
        </FirebaseProvider>
      </body>
    </html>
  );
}
